### ISSUE TITLE
support dot in attribute value

### ISSUE THREAD

**Issue by lttb** [lttb/reshadow#158]
Support dots in attribute value:

```css
Typography[use|variant="notification.description"] {
    color: green
}
```

```js
<Typography use:variant="notification.description" />
```
